# Generated by Django 4.2.10 on 2024-03-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mh_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='excercise_time',
            new_name='exercise_time',
        ),
    ]
