# Generated by Django 4.2.11 on 2024-03-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_tracker', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pdf', models.FileField(upload_to='resources/')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='resources/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_journal',
            field=models.BooleanField(default=False, verbose_name='Afternoon Journal?'),
        ),
    ]
