# Generated by Django 4.2.11 on 2024-03-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_tracker', '0003_substanceabusetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substanceabusetracking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
