# Generated by Django 4.2.10 on 2024-03-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_tracker', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_journal',
            field=models.BooleanField(default=False, verbose_name='Afternoon Journal?'),
        ),
    ]
